/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7NLRADCsDwL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function main() {
  return (
    <>
      <header className="w-full bg-gray-900 py-6 text-white">
        <div className="container mx-auto flex items-center justify-between px-4 md:px-6">
          <div className="flex items-center">
            <GithubIcon className="h-8 w-8 mr-2" />
            <span className="text-xl font-bold">Hackathon Platform</span>
          </div>
          <nav className="hidden md:flex space-x-4">
            <Link className="hover:underline" href="#">
              Upcoming Hackathons
            </Link>
            <Link className="hover:underline" href="#">
              Past Hackathons
            </Link>
            <Link className="hover:underline" href="#">
              Submit Proposal
            </Link>
          </nav>
          <Button variant="primary">Register</Button>
        </div>
      </header>
      <main>
        <section className="bg-gray-900 py-20 text-white">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-4xl font-bold mb-4">Unleash Your Creativity at Our Hackathons</h1>
                <p className="text-lg mb-8">
                  Join our vibrant community of developers, designers, and innovators to tackle real-world challenges
                  and build amazing projects.
                </p>
                <Button variant="primary">Register for Hackathon</Button>
              </div>
              <div>
                <img
                  alt="Hackathon"
                  className="rounded-lg"
                  height="400"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width="600"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-16">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Upcoming Hackathons</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Sustainable Solutions Hackathon</h3>
                  <p className="text-gray-500 mb-4">June 1-3, 2023 | San Francisco, CA</p>
                  <p>Join us in creating innovative solutions to address environmental challenges.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="primary">Learn More</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Fintech Innovation Hackathon</h3>
                  <p className="text-gray-500 mb-4">July 15-17, 2023 | New York, NY</p>
                  <p>Revolutionize the financial industry with your cutting-edge fintech ideas.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="primary">Learn More</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Healthcare Innovation Hackathon</h3>
                  <p className="text-gray-500 mb-4">September 1-3, 2023 | Boston, MA</p>
                  <p>Help improve healthcare outcomes with your innovative solutions.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="primary">Learn More</Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-16">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Past Hackathons</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Sustainability Hackathon 2022</h3>
                  <p className="text-gray-500 mb-4">June 3-5, 2022 | San Francisco, CA</p>
                  <p>Participants created innovative solutions to address environmental challenges.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="link">View Projects</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Fintech Hackathon 2021</h3>
                  <p className="text-gray-500 mb-4">July 16-18, 2021 | New York, NY</p>
                  <p>Developers and designers collaborated to build cutting-edge fintech solutions.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="link">View Projects</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Healthcare Hackathon 2020</h3>
                  <p className="text-gray-500 mb-4">September 4-6, 2020 | Boston, MA</p>
                  <p>Participants created innovative solutions to improve healthcare outcomes.</p>
                </CardContent>
                <CardFooter>
                  <Button variant="link">View Projects</Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-16">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Submit a Hackathon Proposal</h2>
            <Card>
              <CardContent>
                <form className="space-y-4">
                  <div>
                    <Label htmlFor="title">Hackathon Title</Label>
                    <Input id="title" placeholder="Enter hackathon title" />
                  </div>
                  <div>
                    <Label htmlFor="description">Description</Label>
                    <Textarea id="description" placeholder="Provide a brief description of the hackathon" />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="date">Date</Label>
                      <Input id="date" type="date" />
                    </div>
                    <div>
                      <Label htmlFor="location">Location</Label>
                      <Input id="location" placeholder="Enter location" />
                    </div>
                  </div>
                  <div>
                    <Label htmlFor="organizer">Organizer</Label>
                    <Input id="organizer" placeholder="Enter organizer name" />
                  </div>
                </form>
              </CardContent>
              <CardFooter>
                <Button variant="primary">Submit Proposal</Button>
              </CardFooter>
            </Card>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-6">
        <div className="container mx-auto px-4 md:px-6 flex items-center justify-between">
          <div className="flex items-center">
            <GithubIcon className="h-6 w-6 mr-2" />
            <span className="text-lg font-bold">Hackathon Platform</span>
          </div>
          <nav className="hidden md:flex space-x-4">
            <Link className="hover:underline" href="#">
              Terms of Service
            </Link>
            <Link className="hover:underline" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:underline" href="#">
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </>
  )
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
